### ISSUE TITLE
Flutter 3 WidgetsBinding issue

### ISSUE THREAD

**Issue by noga-dev** [wjuniorgit/loop_page_view#11]
For anyone coming here with the WidgetsBinding issue update your pubspec with the below code until #10 gets merged:

```yaml
dependency_overrides:
  loop_page_view:
    git:
      url: https://github.com/noga-dev/loop_page_view.git
      ref: 392e07a96363986697607898058b18b9f3ef312b
```
